/*
 * http.c - A simple, iterative HTTP/1.0 Web server that uses the
 *     GET method to serve static content.
 *
 * This server uses threads to serve client.
 */
#include "csapp.h"

void doit(int fd);
void print_requesthdrs(rio_t *rp);
void parse_uri(char *uri, char *filename);
void serve_static(int fd, char *filename, int filesize);
void get_filetype(char *filename, char *filetype);
void clienterror(int fd, char *cause, char *errnum,
                 char *shortmsg, char *longmsg);

/*
 * This server uses threads to serve client.
 */
void* thread(void *vargp) {
	int connfd = *((int*)vargp);
	Pthread_detach(pthread_self());	// Detach new thread from main.
	Free(vargp);					// Free dynamically allocated memory
	doit(connfd);
	Close(connfd);					// Close the file descriptor
	return NULL;
}

//-----------------------------------------------------------------------------
int main(int argc, char **argv)
{
/*
 * main: 
 *  listens for connections on the given port number, handles HTTP requests 
 *  with the doit function then closes the connection 
 */ 
  
	int listenfd, port, clientlen;
	int *connfdp;
	struct sockaddr_in clientaddr;
	pthread_t tid;
  
	if (argc != 2) {
		fprintf(stderr, "usage: %s <port>\n", argv[0]);
		exit(1);
	}

	if (argv[1][0] < '0' || '9' < argv[1][0]) {
		fprintf(stderr, "port number should be an integer\n");
		exit(1);
	}

	port = atoi(argv[1]);
	listenfd = Open_listenfd(port);
	clientlen = sizeof(clientaddr);

	while (1) {
		connfdp = Malloc(sizeof(int));
		*connfdp = Accept(listenfd, (SA *)&clientaddr, &clientlen);
		Pthread_create(&tid, NULL, thread, connfdp);
	}
}

//-----------------------------------------------------------------------------
void doit(int fd)
{
/*
 * doit: reads a connection socket. if a correct HTTP request and method
 *        is sent, it processes the request via serve_static().
 *        Otherwise, it reports an error via clienterror().
 * params:
 *    - fd (int): file descriptor of connection socket.
 *
 */

	struct stat sbuf;
	char buf[MAXLINE], method[MAXLINE], uri[MAXLINE], version[MAXLINE];
	char filename[MAXLINE];

	// read and store the first line of the HTTP request in the corresponding
	// variables (format: method uri and version)
	rio_t rio;

	Rio_readinitb(&rio, fd);
	Rio_readlineb(&rio, buf, MAXLINE);
	printf("Request headers:\n");
	printf("%s", buf);
	sscanf(buf, "%s %s %s", method, uri, version);

	// Check if the method is GET, if not return a 501 error using clienterror()
	if (strcasecmp(method, "GET")) {
		clienterror(fd, method, "501", "Not implemented",
				"Request method is not supported");
		return;
	}
	
	print_requesthdrs(&rio);

	// If the method is GET, first: call the parse_uri function
	parse_uri(uri, filename);	// This returns a path from a given uri

	// Check if the requested path exists, if not return 404 Error
	if (stat(filename, &sbuf) < 0) {
		clienterror(fd, filename, "404", "Not found",
				"Cannot find this file");
		return;
	}

	// Check if the requested path is a directory if so return 403 error
	if (S_ISDIR(sbuf.st_mode)) {
		clienterror(fd, filename, "403", "Forbidden",
				"Request for directory. Permission Denied");
		return;
	}

	// If the file exists serve it to the client
	serve_static(fd, filename, sbuf.st_size);
}

//-----------------------------------------------------------------------------
void serve_static(int fd, char *filename, int filesize)
{
/*
 * serve_static: 
 *        builds and sends static HTTP requests to the client specified 
 *        by the fd argument
 * params:
 *    - fd: file descriptor of connection socket.
 *    - filename: local path to file
 *    - filesize: size of requested file
 * return: void
 */    
	
	int srcfd;
	char *srcp, filetype[MAXLINE], rbuf[MAXBUF];

	// First check the file type using get_filetype.
	get_filetype(filename, filetype);

	/* Send the HTTP response header to the client */
	// Build valid response header and send to client
	sprintf(rbuf, "HTTP/1.0 200 OK\r\n");
	sprintf(rbuf, "%sServer: Mini Web server\r\n", rbuf);
	sprintf(rbuf, "%sContent-Length: %d\r\n", rbuf, filesize);
	sprintf(rbuf, "%sContent-Type: %s\r\n\r\n", rbuf, filetype);
	Rio_writen(fd, rbuf, strlen(rbuf));

	printf("Response headers: \n");
	printf("%s", rbuf);

	/* Send the file content to the client */
	// Open the file
	srcfd = Open(filename, O_RDONLY, 0);
	
	// Copy it to the srcp buffer
	srcp = Mmap(0, filesize, PROT_READ, MAP_PRIVATE, srcfd, 0);
	Close(srcfd);

	// Write this to the client
	Rio_writen(fd, srcp, filesize);
	Munmap(srcp, filesize);
}

//-----------------------------------------------------------------------------
void get_filetype(char *filename, char *filetype)
{
/*
 * get_filetype: 
 *        given a filename puts the correct HTTP filetype in the filetype variable 
 *        by the fd argument
 * params:
 *    - filename: the filename as a path (generated by parse_uri)
 *    - filetype: the MIME type that will be included in the response to the client 
 */
	if (strstr(filename, ".html"))
		strcpy(filetype, "text/html");
	else if (strstr(filename, ".gif"))	// gif
		strcpy(filetype, "image/gif");
	else if (strstr(filename, ".png"))	// png
		strcpy(filetype, "image/png");
	else if (strstr(filename, ".jpg"))	// jpg
		strcpy(filetype, "image/jpg");
	else
		strcpy(filetype, "text/plain");
}

//-----------------------------------------------------------------------------
void print_requesthdrs(rio_t *rp)
{
/**** DO NOT MODIFY ****/
/**** WARNING: This will read out everything remaining until a line break ****/
/* 
 * print_requesthdrs: 
 *        reads out and prints all request lines sent to the server
 * params:
 *    - rp: Rio pointer for reading from file
 *
 */
  char buf[MAXLINE];
  Rio_readlineb(rp, buf, MAXLINE);
  while(strcmp(buf, "\r\n")) {
    printf("%s", buf);
    Rio_readlineb(rp, buf, MAXLINE);
  }
  printf("\n");
  return;
}

//-----------------------------------------------------------------------------
void parse_uri(char *uri, char *filename)
{
/**** DO NOT MODIFY ****/
/*
 * parse_uri: 
 *        parses uri to give a local filepath, stores this in filename
 * params:
 *    - uri: uri string (input)
 *    - filename: local filepath (output)
 *
 */
  strcpy(filename, ".");
  strcat(filename, uri);
  sscanf(uri, "http://%*[^/]/%s", filename);
}

//-----------------------------------------------------------------------------
void clienterror(int fd, char *cause, char *errnum,
                 char *shortmsg, char *longmsg)
{
/**** DO NOT MODIFY ****/
/*
 * clienterror: 
 *        Creates appropriate HTML error page and sends to the client 
 * params:
 *    - fd: file descriptor of connection socket.
 *    - cause: what has caused the error: the filename or the method
 *    - errnum: The HTTP status (error) code
 *    - shortmsg: The HTTP status (error) message
 *    - longmsg: A longer description of the error that will be printed 
 *           on the error page
 *
 */  
  char buf[MAXLINE], body[MAXBUF];

  /* Build the HTTP response body */
  sprintf(body, "<html><title>Mini Error</title>");
  sprintf(body, "%s<body bgcolor=""ffffff"">\r\n", body);
  sprintf(body, "%s<b>%s: %s</b>\r\n", body, errnum, shortmsg);
  sprintf(body, "%s<p>%s: %s\r\n", body, longmsg, cause);
  sprintf(body, "%s<hr><em>Mini Web server</em>\r\n", body);

  /* Print the HTTP response */
  sprintf(buf, "HTTP/1.0 %s %s\r\n", errnum, shortmsg);
  Rio_writen(fd, buf, strlen(buf));
  sprintf(buf, "Content-type: text/html\r\n");
  Rio_writen(fd, buf, strlen(buf));
  sprintf(buf, "Content-Length: %d\r\n\r\n", (int)strlen(body));
  Rio_writen(fd, buf, strlen(buf));
  Rio_writen(fd, body, strlen(body));
}
